
name: Deploy to Server

on:
  push:
    branches:
      - main # ajusta la rama según tus necesidades

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      run: |
        $ ssh root@172.233.175.48 -p 2300 'cd cd losemiliosAPP/emilios-api && git pull origin main && npm run uild  && pm2  emiliosAPI'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
